service: expressAWS52 #Name of your App

provider:
 name: aws
 runtime: nodejs10.x # Node JS version
 memorySize: 512
 timeout: 60
 stage: production
 region: ca-central-1 # AWS region

functions:
 api:
   handler: lambda.handler   # index.handler 
   events:
     - http: ANY {proxy+}
     - http: ANY /